"""empty message

Revision ID: 2885a955ed07
Revises: 91b244f77269
Create Date: 2017-04-08 13:21:56.861000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2885a955ed07'
down_revision = '91b244f77269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'avatar')
    # ### end Alembic commands ###
