"""empty message

Revision ID: 478e8a4a32c3
Revises: 2885a955ed07
Create Date: 2017-04-08 23:50:16.252000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478e8a4a32c3'
down_revision = '2885a955ed07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('old_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'old_login_time')
    # ### end Alembic commands ###
